version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  test:
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - postgres
    command: bash -c 'sleep 30 && npm test'