version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo
  test:
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - postgres
    command: bash -c 'sleep 30 && POSTGRES_USER=user POSTGRES_PASSWORD=admin POSTGRES_DB=todo npm test'