version: '2'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_db
  test:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres
    command: bash -c '/usr/src/app/test-script.sh'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_db
      - POSTGRES_HOST=postgres